// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package protobuffer;

public final class Login {
  private Login() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuffer_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuffer_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuffer_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuffer_LoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Login.proto\022\013protobuffer\"2\n\014LoginReque" +
      "st\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"1" +
      "\n\rLoginResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007mess" +
      "age\030\002 \001(\t2N\n\014LoginService\022>\n\005login\022\031.pro" +
      "tobuffer.LoginRequest\032\032.protobuffer.Logi" +
      "nResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuffer_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuffer_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuffer_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_protobuffer_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuffer_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuffer_LoginResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
