// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorkoutPlan.proto

package resep3.javat3.protobuf;

public interface DeleteWorkoutPlanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteWorkoutPlanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 wpid = 1;</code>
   * @return The wpid.
   */
  int getWpid();
}
