// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorkoutPlan.proto

package resep3.javat3.protobuf;

public interface emptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:empty)
    com.google.protobuf.MessageOrBuilder {
}
