// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorkoutPlan.proto

package resep3.javat3.protobuf;

public interface GetWorkoutPlanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetWorkoutPlanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 wpid = 1;</code>
   * @return Whether the wpid field is set.
   */
  boolean hasWpid();
  /**
   * <code>optional int32 wpid = 1;</code>
   * @return The wpid.
   */
  int getWpid();

  /**
   * <code>optional int32 userid = 2;</code>
   * @return Whether the userid field is set.
   */
  boolean hasUserid();
  /**
   * <code>optional int32 userid = 2;</code>
   * @return The userid.
   */
  int getUserid();

  /**
   * <code>optional string WPName = 3;</code>
   * @return Whether the wPName field is set.
   */
  boolean hasWPName();
  /**
   * <code>optional string WPName = 3;</code>
   * @return The wPName.
   */
  java.lang.String getWPName();
  /**
   * <code>optional string WPName = 3;</code>
   * @return The bytes for wPName.
   */
  com.google.protobuf.ByteString
      getWPNameBytes();
}
