// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorkoutPlan.proto

package resep3.javat3.protobuf;

public interface GetWorkoutPlanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetWorkoutPlanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .WPData data = 1;</code>
   */
  java.util.List<resep3.javat3.protobuf.WPData> 
      getDataList();
  /**
   * <code>repeated .WPData data = 1;</code>
   */
  resep3.javat3.protobuf.WPData getData(int index);
  /**
   * <code>repeated .WPData data = 1;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .WPData data = 1;</code>
   */
  java.util.List<? extends resep3.javat3.protobuf.WPDataOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .WPData data = 1;</code>
   */
  resep3.javat3.protobuf.WPDataOrBuilder getDataOrBuilder(
      int index);
}
