// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorkoutPlan.proto

package resep3.javat3.protobuf;

/**
 * Protobuf type {@code GetWorkoutPlanRequest}
 */
public final class GetWorkoutPlanRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:GetWorkoutPlanRequest)
    GetWorkoutPlanRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetWorkoutPlanRequest.newBuilder() to construct.
  private GetWorkoutPlanRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetWorkoutPlanRequest() {
    wPName_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetWorkoutPlanRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetWorkoutPlanRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            wpid_ = input.readInt32();
            break;
          }
          case 16: {
            bitField0_ |= 0x00000002;
            userid_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            bitField0_ |= 0x00000004;
            wPName_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return resep3.javat3.protobuf.WorkoutPlan.internal_static_GetWorkoutPlanRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return resep3.javat3.protobuf.WorkoutPlan.internal_static_GetWorkoutPlanRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            resep3.javat3.protobuf.GetWorkoutPlanRequest.class, resep3.javat3.protobuf.GetWorkoutPlanRequest.Builder.class);
  }

  private int bitField0_;
  public static final int WPID_FIELD_NUMBER = 1;
  private int wpid_;
  /**
   * <code>optional int32 wpid = 1;</code>
   * @return Whether the wpid field is set.
   */
  @java.lang.Override
  public boolean hasWpid() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional int32 wpid = 1;</code>
   * @return The wpid.
   */
  @java.lang.Override
  public int getWpid() {
    return wpid_;
  }

  public static final int USERID_FIELD_NUMBER = 2;
  private int userid_;
  /**
   * <code>optional int32 userid = 2;</code>
   * @return Whether the userid field is set.
   */
  @java.lang.Override
  public boolean hasUserid() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional int32 userid = 2;</code>
   * @return The userid.
   */
  @java.lang.Override
  public int getUserid() {
    return userid_;
  }

  public static final int WPNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object wPName_;
  /**
   * <code>optional string WPName = 3;</code>
   * @return Whether the wPName field is set.
   */
  @java.lang.Override
  public boolean hasWPName() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string WPName = 3;</code>
   * @return The wPName.
   */
  @java.lang.Override
  public java.lang.String getWPName() {
    java.lang.Object ref = wPName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      wPName_ = s;
      return s;
    }
  }
  /**
   * <code>optional string WPName = 3;</code>
   * @return The bytes for wPName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWPNameBytes() {
    java.lang.Object ref = wPName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wPName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt32(1, wpid_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeInt32(2, userid_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, wPName_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, wpid_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, userid_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, wPName_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof resep3.javat3.protobuf.GetWorkoutPlanRequest)) {
      return super.equals(obj);
    }
    resep3.javat3.protobuf.GetWorkoutPlanRequest other = (resep3.javat3.protobuf.GetWorkoutPlanRequest) obj;

    if (hasWpid() != other.hasWpid()) return false;
    if (hasWpid()) {
      if (getWpid()
          != other.getWpid()) return false;
    }
    if (hasUserid() != other.hasUserid()) return false;
    if (hasUserid()) {
      if (getUserid()
          != other.getUserid()) return false;
    }
    if (hasWPName() != other.hasWPName()) return false;
    if (hasWPName()) {
      if (!getWPName()
          .equals(other.getWPName())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasWpid()) {
      hash = (37 * hash) + WPID_FIELD_NUMBER;
      hash = (53 * hash) + getWpid();
    }
    if (hasUserid()) {
      hash = (37 * hash) + USERID_FIELD_NUMBER;
      hash = (53 * hash) + getUserid();
    }
    if (hasWPName()) {
      hash = (37 * hash) + WPNAME_FIELD_NUMBER;
      hash = (53 * hash) + getWPName().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static resep3.javat3.protobuf.GetWorkoutPlanRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static resep3.javat3.protobuf.GetWorkoutPlanRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static resep3.javat3.protobuf.GetWorkoutPlanRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static resep3.javat3.protobuf.GetWorkoutPlanRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static resep3.javat3.protobuf.GetWorkoutPlanRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static resep3.javat3.protobuf.GetWorkoutPlanRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static resep3.javat3.protobuf.GetWorkoutPlanRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static resep3.javat3.protobuf.GetWorkoutPlanRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static resep3.javat3.protobuf.GetWorkoutPlanRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static resep3.javat3.protobuf.GetWorkoutPlanRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static resep3.javat3.protobuf.GetWorkoutPlanRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static resep3.javat3.protobuf.GetWorkoutPlanRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(resep3.javat3.protobuf.GetWorkoutPlanRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code GetWorkoutPlanRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:GetWorkoutPlanRequest)
      resep3.javat3.protobuf.GetWorkoutPlanRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return resep3.javat3.protobuf.WorkoutPlan.internal_static_GetWorkoutPlanRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return resep3.javat3.protobuf.WorkoutPlan.internal_static_GetWorkoutPlanRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              resep3.javat3.protobuf.GetWorkoutPlanRequest.class, resep3.javat3.protobuf.GetWorkoutPlanRequest.Builder.class);
    }

    // Construct using resep3.javat3.protobuf.GetWorkoutPlanRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      wpid_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      userid_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      wPName_ = "";
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return resep3.javat3.protobuf.WorkoutPlan.internal_static_GetWorkoutPlanRequest_descriptor;
    }

    @java.lang.Override
    public resep3.javat3.protobuf.GetWorkoutPlanRequest getDefaultInstanceForType() {
      return resep3.javat3.protobuf.GetWorkoutPlanRequest.getDefaultInstance();
    }

    @java.lang.Override
    public resep3.javat3.protobuf.GetWorkoutPlanRequest build() {
      resep3.javat3.protobuf.GetWorkoutPlanRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public resep3.javat3.protobuf.GetWorkoutPlanRequest buildPartial() {
      resep3.javat3.protobuf.GetWorkoutPlanRequest result = new resep3.javat3.protobuf.GetWorkoutPlanRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.wpid_ = wpid_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.userid_ = userid_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        to_bitField0_ |= 0x00000004;
      }
      result.wPName_ = wPName_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof resep3.javat3.protobuf.GetWorkoutPlanRequest) {
        return mergeFrom((resep3.javat3.protobuf.GetWorkoutPlanRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(resep3.javat3.protobuf.GetWorkoutPlanRequest other) {
      if (other == resep3.javat3.protobuf.GetWorkoutPlanRequest.getDefaultInstance()) return this;
      if (other.hasWpid()) {
        setWpid(other.getWpid());
      }
      if (other.hasUserid()) {
        setUserid(other.getUserid());
      }
      if (other.hasWPName()) {
        bitField0_ |= 0x00000004;
        wPName_ = other.wPName_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      resep3.javat3.protobuf.GetWorkoutPlanRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (resep3.javat3.protobuf.GetWorkoutPlanRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int wpid_ ;
    /**
     * <code>optional int32 wpid = 1;</code>
     * @return Whether the wpid field is set.
     */
    @java.lang.Override
    public boolean hasWpid() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional int32 wpid = 1;</code>
     * @return The wpid.
     */
    @java.lang.Override
    public int getWpid() {
      return wpid_;
    }
    /**
     * <code>optional int32 wpid = 1;</code>
     * @param value The wpid to set.
     * @return This builder for chaining.
     */
    public Builder setWpid(int value) {
      bitField0_ |= 0x00000001;
      wpid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 wpid = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWpid() {
      bitField0_ = (bitField0_ & ~0x00000001);
      wpid_ = 0;
      onChanged();
      return this;
    }

    private int userid_ ;
    /**
     * <code>optional int32 userid = 2;</code>
     * @return Whether the userid field is set.
     */
    @java.lang.Override
    public boolean hasUserid() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 userid = 2;</code>
     * @return The userid.
     */
    @java.lang.Override
    public int getUserid() {
      return userid_;
    }
    /**
     * <code>optional int32 userid = 2;</code>
     * @param value The userid to set.
     * @return This builder for chaining.
     */
    public Builder setUserid(int value) {
      bitField0_ |= 0x00000002;
      userid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 userid = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserid() {
      bitField0_ = (bitField0_ & ~0x00000002);
      userid_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object wPName_ = "";
    /**
     * <code>optional string WPName = 3;</code>
     * @return Whether the wPName field is set.
     */
    public boolean hasWPName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string WPName = 3;</code>
     * @return The wPName.
     */
    public java.lang.String getWPName() {
      java.lang.Object ref = wPName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wPName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string WPName = 3;</code>
     * @return The bytes for wPName.
     */
    public com.google.protobuf.ByteString
        getWPNameBytes() {
      java.lang.Object ref = wPName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wPName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string WPName = 3;</code>
     * @param value The wPName to set.
     * @return This builder for chaining.
     */
    public Builder setWPName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      wPName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string WPName = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWPName() {
      bitField0_ = (bitField0_ & ~0x00000004);
      wPName_ = getDefaultInstance().getWPName();
      onChanged();
      return this;
    }
    /**
     * <code>optional string WPName = 3;</code>
     * @param value The bytes for wPName to set.
     * @return This builder for chaining.
     */
    public Builder setWPNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      bitField0_ |= 0x00000004;
      wPName_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:GetWorkoutPlanRequest)
  }

  // @@protoc_insertion_point(class_scope:GetWorkoutPlanRequest)
  private static final resep3.javat3.protobuf.GetWorkoutPlanRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new resep3.javat3.protobuf.GetWorkoutPlanRequest();
  }

  public static resep3.javat3.protobuf.GetWorkoutPlanRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetWorkoutPlanRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetWorkoutPlanRequest>() {
    @java.lang.Override
    public GetWorkoutPlanRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetWorkoutPlanRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetWorkoutPlanRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetWorkoutPlanRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public resep3.javat3.protobuf.GetWorkoutPlanRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

