// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorkoutPlan.proto

package resep3.javat3.protobuf;

/**
 * Protobuf type {@code WorkoutPlanRequest}
 */
public final class WorkoutPlanRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:WorkoutPlanRequest)
    WorkoutPlanRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WorkoutPlanRequest.newBuilder() to construct.
  private WorkoutPlanRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WorkoutPlanRequest() {
    wpName_ = "";
    type_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WorkoutPlanRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private WorkoutPlanRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            wpName_ = s;
            break;
          }
          case 16: {

            timeGoal_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 32: {

            userID_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return resep3.javat3.protobuf.WorkoutPlanOuterClass.internal_static_WorkoutPlanRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return resep3.javat3.protobuf.WorkoutPlanOuterClass.internal_static_WorkoutPlanRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            resep3.javat3.protobuf.WorkoutPlanRequest.class, resep3.javat3.protobuf.WorkoutPlanRequest.Builder.class);
  }

  public static final int WPNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object wpName_;
  /**
   * <code>string wpName = 1;</code>
   * @return The wpName.
   */
  @java.lang.Override
  public java.lang.String getWpName() {
    java.lang.Object ref = wpName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      wpName_ = s;
      return s;
    }
  }
  /**
   * <code>string wpName = 1;</code>
   * @return The bytes for wpName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWpNameBytes() {
    java.lang.Object ref = wpName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      wpName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMEGOAL_FIELD_NUMBER = 2;
  private int timeGoal_;
  /**
   * <code>int32 timeGoal = 2;</code>
   * @return The timeGoal.
   */
  @java.lang.Override
  public int getTimeGoal() {
    return timeGoal_;
  }

  public static final int TYPE_FIELD_NUMBER = 3;
  private volatile java.lang.Object type_;
  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERID_FIELD_NUMBER = 4;
  private int userID_;
  /**
   * <code>int32 userID = 4;</code>
   * @return The userID.
   */
  @java.lang.Override
  public int getUserID() {
    return userID_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(wpName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, wpName_);
    }
    if (timeGoal_ != 0) {
      output.writeInt32(2, timeGoal_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
    }
    if (userID_ != 0) {
      output.writeInt32(4, userID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(wpName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, wpName_);
    }
    if (timeGoal_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, timeGoal_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
    }
    if (userID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, userID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof resep3.javat3.protobuf.WorkoutPlanRequest)) {
      return super.equals(obj);
    }
    resep3.javat3.protobuf.WorkoutPlanRequest other = (resep3.javat3.protobuf.WorkoutPlanRequest) obj;

    if (!getWpName()
        .equals(other.getWpName())) return false;
    if (getTimeGoal()
        != other.getTimeGoal()) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (getUserID()
        != other.getUserID()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + WPNAME_FIELD_NUMBER;
    hash = (53 * hash) + getWpName().hashCode();
    hash = (37 * hash) + TIMEGOAL_FIELD_NUMBER;
    hash = (53 * hash) + getTimeGoal();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + getUserID();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static resep3.javat3.protobuf.WorkoutPlanRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static resep3.javat3.protobuf.WorkoutPlanRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static resep3.javat3.protobuf.WorkoutPlanRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static resep3.javat3.protobuf.WorkoutPlanRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static resep3.javat3.protobuf.WorkoutPlanRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static resep3.javat3.protobuf.WorkoutPlanRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static resep3.javat3.protobuf.WorkoutPlanRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static resep3.javat3.protobuf.WorkoutPlanRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static resep3.javat3.protobuf.WorkoutPlanRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static resep3.javat3.protobuf.WorkoutPlanRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static resep3.javat3.protobuf.WorkoutPlanRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static resep3.javat3.protobuf.WorkoutPlanRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(resep3.javat3.protobuf.WorkoutPlanRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code WorkoutPlanRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:WorkoutPlanRequest)
      resep3.javat3.protobuf.WorkoutPlanRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return resep3.javat3.protobuf.WorkoutPlanOuterClass.internal_static_WorkoutPlanRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return resep3.javat3.protobuf.WorkoutPlanOuterClass.internal_static_WorkoutPlanRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              resep3.javat3.protobuf.WorkoutPlanRequest.class, resep3.javat3.protobuf.WorkoutPlanRequest.Builder.class);
    }

    // Construct using resep3.javat3.protobuf.WorkoutPlanRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      wpName_ = "";

      timeGoal_ = 0;

      type_ = "";

      userID_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return resep3.javat3.protobuf.WorkoutPlanOuterClass.internal_static_WorkoutPlanRequest_descriptor;
    }

    @java.lang.Override
    public resep3.javat3.protobuf.WorkoutPlanRequest getDefaultInstanceForType() {
      return resep3.javat3.protobuf.WorkoutPlanRequest.getDefaultInstance();
    }

    @java.lang.Override
    public resep3.javat3.protobuf.WorkoutPlanRequest build() {
      resep3.javat3.protobuf.WorkoutPlanRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public resep3.javat3.protobuf.WorkoutPlanRequest buildPartial() {
      resep3.javat3.protobuf.WorkoutPlanRequest result = new resep3.javat3.protobuf.WorkoutPlanRequest(this);
      result.wpName_ = wpName_;
      result.timeGoal_ = timeGoal_;
      result.type_ = type_;
      result.userID_ = userID_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof resep3.javat3.protobuf.WorkoutPlanRequest) {
        return mergeFrom((resep3.javat3.protobuf.WorkoutPlanRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(resep3.javat3.protobuf.WorkoutPlanRequest other) {
      if (other == resep3.javat3.protobuf.WorkoutPlanRequest.getDefaultInstance()) return this;
      if (!other.getWpName().isEmpty()) {
        wpName_ = other.wpName_;
        onChanged();
      }
      if (other.getTimeGoal() != 0) {
        setTimeGoal(other.getTimeGoal());
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (other.getUserID() != 0) {
        setUserID(other.getUserID());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      resep3.javat3.protobuf.WorkoutPlanRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (resep3.javat3.protobuf.WorkoutPlanRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object wpName_ = "";
    /**
     * <code>string wpName = 1;</code>
     * @return The wpName.
     */
    public java.lang.String getWpName() {
      java.lang.Object ref = wpName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        wpName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string wpName = 1;</code>
     * @return The bytes for wpName.
     */
    public com.google.protobuf.ByteString
        getWpNameBytes() {
      java.lang.Object ref = wpName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        wpName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string wpName = 1;</code>
     * @param value The wpName to set.
     * @return This builder for chaining.
     */
    public Builder setWpName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      wpName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string wpName = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearWpName() {
      
      wpName_ = getDefaultInstance().getWpName();
      onChanged();
      return this;
    }
    /**
     * <code>string wpName = 1;</code>
     * @param value The bytes for wpName to set.
     * @return This builder for chaining.
     */
    public Builder setWpNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      wpName_ = value;
      onChanged();
      return this;
    }

    private int timeGoal_ ;
    /**
     * <code>int32 timeGoal = 2;</code>
     * @return The timeGoal.
     */
    @java.lang.Override
    public int getTimeGoal() {
      return timeGoal_;
    }
    /**
     * <code>int32 timeGoal = 2;</code>
     * @param value The timeGoal to set.
     * @return This builder for chaining.
     */
    public Builder setTimeGoal(int value) {
      
      timeGoal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 timeGoal = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeGoal() {
      
      timeGoal_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <code>string type = 3;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type = 3;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type = 3;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <code>string type = 3;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private int userID_ ;
    /**
     * <code>int32 userID = 4;</code>
     * @return The userID.
     */
    @java.lang.Override
    public int getUserID() {
      return userID_;
    }
    /**
     * <code>int32 userID = 4;</code>
     * @param value The userID to set.
     * @return This builder for chaining.
     */
    public Builder setUserID(int value) {
      
      userID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 userID = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserID() {
      
      userID_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:WorkoutPlanRequest)
  }

  // @@protoc_insertion_point(class_scope:WorkoutPlanRequest)
  private static final resep3.javat3.protobuf.WorkoutPlanRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new resep3.javat3.protobuf.WorkoutPlanRequest();
  }

  public static resep3.javat3.protobuf.WorkoutPlanRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WorkoutPlanRequest>
      PARSER = new com.google.protobuf.AbstractParser<WorkoutPlanRequest>() {
    @java.lang.Override
    public WorkoutPlanRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new WorkoutPlanRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<WorkoutPlanRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WorkoutPlanRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public resep3.javat3.protobuf.WorkoutPlanRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

