// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorkoutPlan.proto

package resep3.javat3.protobuf;

public interface WorkoutPlanRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WorkoutPlanRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string wpName = 1;</code>
   * @return The wpName.
   */
  java.lang.String getWpName();
  /**
   * <code>string wpName = 1;</code>
   * @return The bytes for wpName.
   */
  com.google.protobuf.ByteString
      getWpNameBytes();

  /**
   * <code>int32 timeGoal = 2;</code>
   * @return The timeGoal.
   */
  int getTimeGoal();

  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>int32 userID = 4;</code>
   * @return The userID.
   */
  int getUserID();
}
