// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorkoutPlan.proto

package resep3.javat3.protobuf;

public final class WorkoutPlan {
  private WorkoutPlan() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkoutPlanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WorkoutPlanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkoutPlanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WorkoutPlanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetWorkoutPlanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetWorkoutPlanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetWorkoutPlanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetWorkoutPlanResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WPData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WPData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021WorkoutPlan.proto\"T\n\022WorkoutPlanReques" +
      "t\022\016\n\006wpName\030\001 \001(\t\022\020\n\010timeGoal\030\002 \001(\005\022\014\n\004t" +
      "ype\030\003 \001(\t\022\016\n\006userID\030\004 \001(\005\"#\n\023WorkoutPlan" +
      "Response\022\014\n\004wpid\030\001 \001(\005\"s\n\025GetWorkoutPlan" +
      "Request\022\021\n\004wpid\030\001 \001(\005H\000\210\001\001\022\023\n\006userid\030\002 \001" +
      "(\005H\001\210\001\001\022\023\n\006WPName\030\003 \001(\tH\002\210\001\001B\007\n\005_wpidB\t\n" +
      "\007_useridB\t\n\007_WPName\"/\n\026GetWorkoutPlanRes" +
      "ponse\022\025\n\004data\030\001 \003(\0132\007.WPData\"V\n\006WPData\022\014" +
      "\n\004wpid\030\001 \001(\005\022\016\n\006wpname\030\002 \001(\t\022\020\n\010timegoal" +
      "\030\003 \001(\005\022\014\n\004type\030\004 \001(\t\022\016\n\006userid\030\005 \001(\0052\227\001\n" +
      "\022WorkoutPlanService\022>\n\021createWorkoutPlan" +
      "\022\023.WorkoutPlanRequest\032\024.WorkoutPlanRespo" +
      "nse\022A\n\016getWorkoutPlan\022\026.GetWorkoutPlanRe" +
      "quest\032\027.GetWorkoutPlanResponseB\032\n\026resep3" +
      ".javat3.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_WorkoutPlanRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WorkoutPlanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WorkoutPlanRequest_descriptor,
        new java.lang.String[] { "WpName", "TimeGoal", "Type", "UserID", });
    internal_static_WorkoutPlanResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WorkoutPlanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WorkoutPlanResponse_descriptor,
        new java.lang.String[] { "Wpid", });
    internal_static_GetWorkoutPlanRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_GetWorkoutPlanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetWorkoutPlanRequest_descriptor,
        new java.lang.String[] { "Wpid", "Userid", "WPName", "Wpid", "Userid", "WPName", });
    internal_static_GetWorkoutPlanResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetWorkoutPlanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetWorkoutPlanResponse_descriptor,
        new java.lang.String[] { "Data", });
    internal_static_WPData_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_WPData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WPData_descriptor,
        new java.lang.String[] { "Wpid", "Wpname", "Timegoal", "Type", "Userid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
