// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorkoutPlan.proto

package resep3.javat3.protobuf;

public interface WorkoutPlanResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WorkoutPlanResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 wpid = 1;</code>
   * @return The wpid.
   */
  long getWpid();
}
