// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorkoutPlan.proto

package resep3.javat3.protobuf;

public final class WorkoutPlanOuterClass {
  private WorkoutPlanOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkoutPlanRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WorkoutPlanRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WorkoutPlanResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WorkoutPlanResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021WorkoutPlan.proto\"T\n\022WorkoutPlanReques" +
      "t\022\016\n\006wpName\030\001 \001(\t\022\020\n\010timeGoal\030\002 \001(\005\022\014\n\004t" +
      "ype\030\003 \001(\t\022\016\n\006userID\030\004 \001(\005\"#\n\023WorkoutPlan" +
      "Response\022\014\n\004wpid\030\001 \001(\0032M\n\013WorkoutPlan\022>\n" +
      "\021createWorkoutPlan\022\023.WorkoutPlanRequest\032" +
      "\024.WorkoutPlanResponseB\032\n\026resep3.javat3.p" +
      "rotobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_WorkoutPlanRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_WorkoutPlanRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WorkoutPlanRequest_descriptor,
        new java.lang.String[] { "WpName", "TimeGoal", "Type", "UserID", });
    internal_static_WorkoutPlanResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WorkoutPlanResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WorkoutPlanResponse_descriptor,
        new java.lang.String[] { "Wpid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
