// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WorkoutPlan.proto

package resep3.javat3.protobuf;

public interface WPDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WPData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 wpid = 1;</code>
   * @return The wpid.
   */
  int getWpid();

  /**
   * <code>string wpname = 2;</code>
   * @return The wpname.
   */
  java.lang.String getWpname();
  /**
   * <code>string wpname = 2;</code>
   * @return The bytes for wpname.
   */
  com.google.protobuf.ByteString
      getWpnameBytes();

  /**
   * <code>int32 timegoal = 3;</code>
   * @return The timegoal.
   */
  int getTimegoal();

  /**
   * <code>string type = 4;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 4;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>int32 userid = 5;</code>
   * @return The userid.
   */
  int getUserid();
}
